# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AO_imaging_design.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(912, 514)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(912, 0))
        Form.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBoxCenterLateral = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxCenterLateral.setChecked(True)
        self.checkBoxCenterLateral.setObjectName("checkBoxCenterLateral")
        self.gridLayout_4.addWidget(self.checkBoxCenterLateral, 7, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 4, 0, 1, 1)
        self.doubleSpinBoxRange = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxRange.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxRange.setSizePolicy(sizePolicy)
        self.doubleSpinBoxRange.setDecimals(1)
        self.doubleSpinBoxRange.setMinimum(-100.0)
        self.doubleSpinBoxRange.setSingleStep(0.1)
        self.doubleSpinBoxRange.setProperty("value", 10.0)
        self.doubleSpinBoxRange.setObjectName("doubleSpinBoxRange")
        self.gridLayout_4.addWidget(self.doubleSpinBoxRange, 1, 1, 1, 1)
        self.spinBox_maskRadius = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_maskRadius.setMinimum(16)
        self.spinBox_maskRadius.setMaximum(512)
        self.spinBox_maskRadius.setSingleStep(10)
        self.spinBox_maskRadius.setProperty("value", 80)
        self.spinBox_maskRadius.setObjectName("spinBox_maskRadius")
        self.gridLayout_4.addWidget(self.spinBox_maskRadius, 4, 1, 1, 1)
        self.pushButton_Acquire = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Acquire.sizePolicy().hasHeightForWidth())
        self.pushButton_Acquire.setSizePolicy(sizePolicy)
        self.pushButton_Acquire.setObjectName("pushButton_Acquire")
        self.gridLayout_4.addWidget(self.pushButton_Acquire, 11, 0, 1, 2)
        self.lineEdit_cX = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_cX.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_cX.setObjectName("lineEdit_cX")
        self.gridLayout_4.addWidget(self.lineEdit_cX, 5, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 5, 0, 1, 1)
        self.lineEdit_fname = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_fname.setMinimumSize(QtCore.QSize(130, 0))
        self.lineEdit_fname.setObjectName("lineEdit_fname")
        self.gridLayout_4.addWidget(self.lineEdit_fname, 9, 0, 1, 1)
        self.lineEdit_cY = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_cY.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_cY.setObjectName("lineEdit_cY")
        self.gridLayout_4.addWidget(self.lineEdit_cY, 6, 1, 1, 1)
        self.spinBoxSlices = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxSlices.sizePolicy().hasHeightForWidth())
        self.spinBoxSlices.setSizePolicy(sizePolicy)
        self.spinBoxSlices.setReadOnly(False)
        self.spinBoxSlices.setMinimum(3)
        self.spinBoxSlices.setSingleStep(2)
        self.spinBoxSlices.setProperty("value", 21)
        self.spinBoxSlices.setObjectName("spinBoxSlices")
        self.gridLayout_4.addWidget(self.spinBoxSlices, 2, 1, 1, 1)
        self.spinBoxFrames = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxFrames.sizePolicy().hasHeightForWidth())
        self.spinBoxFrames.setSizePolicy(sizePolicy)
        self.spinBoxFrames.setMinimum(1)
        self.spinBoxFrames.setProperty("value", 5)
        self.spinBoxFrames.setObjectName("spinBoxFrames")
        self.gridLayout_4.addWidget(self.spinBoxFrames, 3, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 6, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_fname = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_fname.sizePolicy().hasHeightForWidth())
        self.label_fname.setSizePolicy(sizePolicy)
        self.label_fname.setObjectName("label_fname")
        self.gridLayout_4.addWidget(self.label_fname, 8, 0, 1, 1)
        self.pushButton_run = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_run.sizePolicy().hasHeightForWidth())
        self.pushButton_run.setSizePolicy(sizePolicy)
        self.pushButton_run.setMinimumSize(QtCore.QSize(130, 40))
        self.pushButton_run.setObjectName("pushButton_run")
        self.gridLayout_4.addWidget(self.pushButton_run, 12, 0, 1, 1)
        self.pushButton_position = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_position.setObjectName("pushButton_position")
        self.gridLayout_4.addWidget(self.pushButton_position, 10, 0, 1, 2)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBoxPhase = QtWidgets.QGroupBox(Form)
        self.groupBoxPhase.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxPhase.sizePolicy().hasHeightForWidth())
        self.groupBoxPhase.setSizePolicy(sizePolicy)
        self.groupBoxPhase.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxPhase.setObjectName("groupBoxPhase")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxPhase)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.doubleSpinBoxWavelength = QtWidgets.QDoubleSpinBox(self.groupBoxPhase)
        self.doubleSpinBoxWavelength.setDecimals(3)
        self.doubleSpinBoxWavelength.setProperty("value", 0.515)
        self.doubleSpinBoxWavelength.setObjectName("doubleSpinBoxWavelength")
        self.gridLayout_3.addWidget(self.doubleSpinBoxWavelength, 1, 1, 1, 1)
        self.doubleSpinBoxIndex = QtWidgets.QDoubleSpinBox(self.groupBoxPhase)
        self.doubleSpinBoxIndex.setSingleStep(0.01)
        self.doubleSpinBoxIndex.setProperty("value", 1.33)
        self.doubleSpinBoxIndex.setObjectName("doubleSpinBoxIndex")
        self.gridLayout_3.addWidget(self.doubleSpinBoxIndex, 2, 1, 1, 1)
        self.spinBoxIterations = QtWidgets.QSpinBox(self.groupBoxPhase)
        self.spinBoxIterations.setMinimum(1)
        self.spinBoxIterations.setMaximum(999)
        self.spinBoxIterations.setProperty("value", 20)
        self.spinBoxIterations.setObjectName("spinBoxIterations")
        self.gridLayout_3.addWidget(self.spinBoxIterations, 8, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBoxPhase)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 8, 0, 1, 1)
        self.pushButtonPhase = QtWidgets.QPushButton(self.groupBoxPhase)
        self.pushButtonPhase.setObjectName("pushButtonPhase")
        self.gridLayout_3.addWidget(self.pushButtonPhase, 10, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 16, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBoxPhase)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBoxPhase)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.doubleSpinBoxNA = QtWidgets.QDoubleSpinBox(self.groupBoxPhase)
        self.doubleSpinBoxNA.setSingleStep(0.01)
        self.doubleSpinBoxNA.setProperty("value", 1.0)
        self.doubleSpinBoxNA.setObjectName("doubleSpinBoxNA")
        self.gridLayout_3.addWidget(self.doubleSpinBoxNA, 3, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBoxPhase)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBoxPhase)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.doubleSpinBoxPixel = QtWidgets.QDoubleSpinBox(self.groupBoxPhase)
        self.doubleSpinBoxPixel.setDecimals(3)
        self.doubleSpinBoxPixel.setMaximum(9.0)
        self.doubleSpinBoxPixel.setSingleStep(0.01)
        self.doubleSpinBoxPixel.setProperty("value", 0.102)
        self.doubleSpinBoxPixel.setObjectName("doubleSpinBoxPixel")
        self.gridLayout_3.addWidget(self.doubleSpinBoxPixel, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBoxPhase)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.doubleSpinBoxFocal = QtWidgets.QDoubleSpinBox(self.groupBoxPhase)
        self.doubleSpinBoxFocal.setMaximum(9999.99)
        self.doubleSpinBoxFocal.setProperty("value", 5000.0)
        self.doubleSpinBoxFocal.setObjectName("doubleSpinBoxFocal")
        self.gridLayout_3.addWidget(self.doubleSpinBoxFocal, 4, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBoxPhase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radioButtonPlane = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButtonPlane.setChecked(True)
        self.radioButtonPlane.setObjectName("radioButtonPlane")
        self.gridLayout_2.addWidget(self.radioButtonPlane, 0, 0, 1, 1)
        self.radioButtonMirror = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButtonMirror.setObjectName("radioButtonMirror")
        self.gridLayout_2.addWidget(self.radioButtonMirror, 1, 0, 1, 1)
        self.doubleSpinBoxMirrorDistance = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBoxMirrorDistance.setSingleStep(0.01)
        self.doubleSpinBoxMirrorDistance.setProperty("value", 2.0)
        self.doubleSpinBoxMirrorDistance.setObjectName("doubleSpinBoxMirrorDistance")
        self.gridLayout_2.addWidget(self.doubleSpinBoxMirrorDistance, 1, 1, 1, 1)
        self.radioButtonFromFile = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButtonFromFile.setObjectName("radioButtonFromFile")
        self.gridLayout_2.addWidget(self.radioButtonFromFile, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_4, 7, 0, 1, 3)
        self.label_14 = QtWidgets.QLabel(self.groupBoxPhase)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 13, 0, 1, 1)
        self.pushButton_modUnwrapped = QtWidgets.QPushButton(self.groupBoxPhase)
        self.pushButton_modUnwrapped.setObjectName("pushButton_modUnwrapped")
        self.gridLayout_3.addWidget(self.pushButton_modUnwrapped, 11, 1, 1, 1)
        self.checkBox_ignore4 = QtWidgets.QCheckBox(self.groupBoxPhase)
        self.checkBox_ignore4.setObjectName("checkBox_ignore4")
        self.gridLayout_3.addWidget(self.checkBox_ignore4, 16, 1, 1, 1)
        self.spinBox_numWavelengths = QtWidgets.QSpinBox(self.groupBoxPhase)
        self.spinBox_numWavelengths.setMinimum(1)
        self.spinBox_numWavelengths.setProperty("value", 1)
        self.spinBox_numWavelengths.setObjectName("spinBox_numWavelengths")
        self.gridLayout_3.addWidget(self.spinBox_numWavelengths, 5, 1, 1, 1)
        self.pushButton_zernFitUnwrapped = QtWidgets.QPushButton(self.groupBoxPhase)
        self.pushButton_zernFitUnwrapped.setObjectName("pushButton_zernFitUnwrapped")
        self.gridLayout_3.addWidget(self.pushButton_zernFitUnwrapped, 12, 1, 1, 1)
        self.pushButton_unwrap = QtWidgets.QPushButton(self.groupBoxPhase)
        self.pushButton_unwrap.setObjectName("pushButton_unwrap")
        self.gridLayout_3.addWidget(self.pushButton_unwrap, 10, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBoxPhase)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 5, 0, 1, 1)
        self.spinBox_zernModesToFit = QtWidgets.QSpinBox(self.groupBoxPhase)
        self.spinBox_zernModesToFit.setObjectName("spinBox_zernModesToFit")
        self.gridLayout_3.addWidget(self.spinBox_zernModesToFit, 13, 1, 1, 1)
        self.checkBox_resetAmp = QtWidgets.QCheckBox(self.groupBoxPhase)
        self.checkBox_resetAmp.setObjectName("checkBox_resetAmp")
        self.gridLayout_3.addWidget(self.checkBox_resetAmp, 12, 0, 1, 1)
        self.checkBox_invertPF = QtWidgets.QCheckBox(self.groupBoxPhase)
        self.checkBox_invertPF.setObjectName("checkBox_invertPF")
        self.gridLayout_3.addWidget(self.checkBox_invertPF, 11, 0, 1, 1)
        self.checkBox_symmeterize = QtWidgets.QCheckBox(self.groupBoxPhase)
        self.checkBox_symmeterize.setObjectName("checkBox_symmeterize")
        self.gridLayout_3.addWidget(self.checkBox_symmeterize, 9, 0, 1, 1)
        self.checkBoxNeglectDefocus = QtWidgets.QCheckBox(self.groupBoxPhase)
        self.checkBoxNeglectDefocus.setChecked(True)
        self.checkBoxNeglectDefocus.setObjectName("checkBoxNeglectDefocus")
        self.gridLayout_3.addWidget(self.checkBoxNeglectDefocus, 6, 0, 1, 2)
        self.horizontalLayout.addWidget(self.groupBoxPhase)
        self.tabWidget_viewer = QtWidgets.QTabWidget(Form)
        self.tabWidget_viewer.setObjectName("tabWidget_viewer")
        self.tab_image = QtWidgets.QWidget()
        self.tab_image.setObjectName("tab_image")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_image)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 381, 401))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_image = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_image.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_image.setObjectName("verticalLayout_image")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.mplwidget_xy = MatplotlibWidget(self.verticalLayoutWidget)
        self.mplwidget_xy.setObjectName("mplwidget_xy")
        self.horizontalLayout_3.addWidget(self.mplwidget_xy)
        self.mplwidget_yz = MatplotlibWidget(self.verticalLayoutWidget)
        self.mplwidget_yz.setObjectName("mplwidget_yz")
        self.horizontalLayout_3.addWidget(self.mplwidget_yz)
        self.verticalLayout_image.addLayout(self.horizontalLayout_3)
        self.mplwidget_sharpness = MatplotlibWidget(self.verticalLayoutWidget)
        self.mplwidget_sharpness.setObjectName("mplwidget_sharpness")
        self.verticalLayout_image.addWidget(self.mplwidget_sharpness)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab_image)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 409, 381, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_snap = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_snap.setObjectName("pushButton_snap")
        self.horizontalLayout_4.addWidget(self.pushButton_snap)
        self.tabWidget_viewer.addTab(self.tab_image, "")
        self.tab_pupil = QtWidgets.QWidget()
        self.tab_pupil.setObjectName("tab_pupil")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_pupil)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 371, 381))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.mplwidget_zfit = MatplotlibWidget(self.gridLayoutWidget)
        self.mplwidget_zfit.setObjectName("mplwidget_zfit")
        self.gridLayout.addWidget(self.mplwidget_zfit, 0, 1, 1, 1)
        self.mplwidget_PF = MatplotlibWidget(self.gridLayoutWidget)
        self.mplwidget_PF.setObjectName("mplwidget_PF")
        self.gridLayout.addWidget(self.mplwidget_PF, 0, 0, 1, 1)
        self.mplwidget_sync = MatplotlibWidget(self.gridLayoutWidget)
        self.mplwidget_sync.setObjectName("mplwidget_sync")
        self.gridLayout.addWidget(self.mplwidget_sync, 1, 0, 1, 1)
        self.mplwidget_seg = MatplotlibWidget(self.gridLayoutWidget)
        self.mplwidget_seg.setObjectName("mplwidget_seg")
        self.gridLayout.addWidget(self.mplwidget_seg, 1, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_pupil)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 440, 371, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_zfit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_zfit.sizePolicy().hasHeightForWidth())
        self.pushButton_zfit.setSizePolicy(sizePolicy)
        self.pushButton_zfit.setObjectName("pushButton_zfit")
        self.horizontalLayout_2.addWidget(self.pushButton_zfit)
        self.pushButton_modulate = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_modulate.sizePolicy().hasHeightForWidth())
        self.pushButton_modulate.setSizePolicy(sizePolicy)
        self.pushButton_modulate.setObjectName("pushButton_modulate")
        self.horizontalLayout_2.addWidget(self.pushButton_modulate)
        self.pushButton_save = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_save.sizePolicy().hasHeightForWidth())
        self.pushButton_save.setSizePolicy(sizePolicy)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_2.addWidget(self.pushButton_save)
        self.tabWidget_viewer.addTab(self.tab_pupil, "")
        self.horizontalLayout.addWidget(self.tabWidget_viewer)
        self.groupBoxModulations = QtWidgets.QGroupBox(Form)
        self.groupBoxModulations.setCheckable(True)
        self.groupBoxModulations.setObjectName("groupBoxModulations")
        self.verticalLayoutModulations = QtWidgets.QVBoxLayout(self.groupBoxModulations)
        self.verticalLayoutModulations.setObjectName("verticalLayoutModulations")
        spacerItem1 = QtWidgets.QSpacerItem(20, 317, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayoutModulations.addItem(spacerItem1)
        self.pushButton_sync = QtWidgets.QPushButton(self.groupBoxModulations)
        self.pushButton_sync.setObjectName("pushButton_sync")
        self.verticalLayoutModulations.addWidget(self.pushButton_sync)
        self.horizontalLayout.addWidget(self.groupBoxModulations)

        self.retranslateUi(Form)
        self.tabWidget_viewer.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Adaptive Optics"))
        self.groupBox.setTitle(_translate("Form", "PSF"))
        self.checkBoxCenterLateral.setText(_translate("Form", "Center PSF laterally"))
        self.label_3.setText(_translate("Form", "# Slices:"))
        self.label_4.setText(_translate("Form", "# Frames/slice:"))
        self.label.setText(_translate("Form", "Mask radius:"))
        self.pushButton_Acquire.setText(_translate("Form", "Acquire PSF"))
        self.lineEdit_cX.setText(_translate("Form", "128"))
        self.label_11.setText(_translate("Form", "Center X:"))
        self.lineEdit_cY.setText(_translate("Form", "128"))
        self.label_12.setText(_translate("Form", "Center Y:"))
        self.label_2.setText(_translate("Form", "Range [um]:"))
        self.label_fname.setText(_translate("Form", "Filename"))
        self.pushButton_run.setText(_translate("Form", "run!"))
        self.pushButton_position.setText(_translate("Form", "Set position"))
        self.groupBoxPhase.setTitle(_translate("Form", "Phase retrieval"))
        self.label_10.setText(_translate("Form", "# Iterations:"))
        self.pushButtonPhase.setText(_translate("Form", "Retrieve phase"))
        self.label_9.setText(_translate("Form", "Focal length:"))
        self.label_7.setText(_translate("Form", "Refractive index:"))
        self.label_8.setText(_translate("Form", "NA:"))
        self.label_6.setText(_translate("Form", "Wavelength [um]:"))
        self.label_5.setText(_translate("Form", "Pixel size [um]:"))
        self.groupBox_4.setTitle(_translate("Form", "Initial guess"))
        self.radioButtonPlane.setText(_translate("Form", "Plane wave"))
        self.radioButtonMirror.setText(_translate("Form", "Mirror"))
        self.radioButtonFromFile.setText(_translate("Form", "From file"))
        self.label_14.setText(_translate("Form", "Num modes to fit to:"))
        self.pushButton_modUnwrapped.setText(_translate("Form", "Mod. Unwrpd"))
        self.checkBox_ignore4.setText(_translate("Form", "Ignore 1st 4?"))
        self.pushButton_zernFitUnwrapped.setText(_translate("Form", "Fit Unwrpd"))
        self.pushButton_unwrap.setText(_translate("Form", "Unwrap"))
        self.label_13.setText(_translate("Form", "# Wavelengths:"))
        self.checkBox_resetAmp.setText(_translate("Form", "Reset amplitude?"))
        self.checkBox_invertPF.setText(_translate("Form", "Invert?"))
        self.checkBox_symmeterize.setText(_translate("Form", "Make symmetric?"))
        self.checkBoxNeglectDefocus.setText(_translate("Form", "Neglect defocus"))
        self.pushButton_snap.setText(_translate("Form", "Snap shot"))
        self.tabWidget_viewer.setTabText(self.tabWidget_viewer.indexOf(self.tab_image), _translate("Form", "Images"))
        self.pushButton_zfit.setText(_translate("Form", "Fit"))
        self.pushButton_modulate.setText(_translate("Form", "Modulate"))
        self.pushButton_save.setText(_translate("Form", "Save"))
        self.tabWidget_viewer.setTabText(self.tabWidget_viewer.indexOf(self.tab_pupil), _translate("Form", "Pupils"))
        self.groupBoxModulations.setTitle(_translate("Form", "Modulations"))
        self.pushButton_sync.setText(_translate("Form", "Sync"))

from matplotlibwidget import MatplotlibWidget
