# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fastscan_design.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(940, 743)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(250, 690, 521, 40))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBoxAutoscale = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxAutoscale.setChecked(True)
        self.checkBoxAutoscale.setTristate(False)
        self.checkBoxAutoscale.setObjectName("checkBoxAutoscale")
        self.horizontalLayout.addWidget(self.checkBoxAutoscale)
        self.checkBox_autoscale90 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_autoscale90.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_autoscale90.setAutoFillBackground(False)
        self.checkBox_autoscale90.setObjectName("checkBox_autoscale90")
        self.horizontalLayout.addWidget(self.checkBox_autoscale90)
        self.checkBox_showTarget = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_showTarget.setObjectName("checkBox_showTarget")
        self.horizontalLayout.addWidget(self.checkBox_showTarget)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(250, 30, 211, 461))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_stage = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_stage.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_stage.setObjectName("verticalLayout_stage")
        self.label_start = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_start.setObjectName("label_start")
        self.verticalLayout_stage.addWidget(self.label_start)
        self.lineEdit_startpos = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_startpos.setObjectName("lineEdit_startpos")
        self.verticalLayout_stage.addWidget(self.lineEdit_startpos)
        self.label_end = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_end.setObjectName("label_end")
        self.verticalLayout_stage.addWidget(self.label_end)
        self.lineEdit_endpos = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_endpos.setObjectName("lineEdit_endpos")
        self.verticalLayout_stage.addWidget(self.lineEdit_endpos)
        self.horizontalLayout_posset = QtWidgets.QHBoxLayout()
        self.horizontalLayout_posset.setObjectName("horizontalLayout_posset")
        self.pushButton_seta = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_seta.sizePolicy().hasHeightForWidth())
        self.pushButton_seta.setSizePolicy(sizePolicy)
        self.pushButton_seta.setObjectName("pushButton_seta")
        self.horizontalLayout_posset.addWidget(self.pushButton_seta)
        self.pushButton_setb = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_setb.sizePolicy().hasHeightForWidth())
        self.pushButton_setb.setSizePolicy(sizePolicy)
        self.pushButton_setb.setObjectName("pushButton_setb")
        self.horizontalLayout_posset.addWidget(self.pushButton_setb)
        self.verticalLayout_stage.addLayout(self.horizontalLayout_posset)
        self.label_mrange = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_mrange.setObjectName("label_mrange")
        self.verticalLayout_stage.addWidget(self.label_mrange)
        self.lineEdit_mrange = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_mrange.setObjectName("lineEdit_mrange")
        self.verticalLayout_stage.addWidget(self.lineEdit_mrange)
        self.label_speed = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_speed.setObjectName("label_speed")
        self.verticalLayout_stage.addWidget(self.label_speed)
        self.lineEdit_speed = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_speed.setObjectName("lineEdit_speed")
        self.verticalLayout_stage.addWidget(self.lineEdit_speed)
        self.pushButton_startmv = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_startmv.sizePolicy().hasHeightForWidth())
        self.pushButton_startmv.setSizePolicy(sizePolicy)
        self.pushButton_startmv.setObjectName("pushButton_startmv")
        self.verticalLayout_stage.addWidget(self.pushButton_startmv)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Camera"))
        self.checkBoxAutoscale.setText(_translate("Form", "Autoscale..."))
        self.checkBox_autoscale90.setText(_translate("Form", "...to 75% of max"))
        self.checkBox_showTarget.setText(_translate("Form", "Show Target"))
        self.label_start.setText(_translate("Form", "Start position"))
        self.label_end.setText(_translate("Form", "End position"))
        self.pushButton_seta.setText(_translate("Form", "Set start"))
        self.pushButton_setb.setText(_translate("Form", "Set end"))
        self.label_mrange.setText(_translate("Form", "Motion range"))
        self.label_speed.setText(_translate("Form", "Motion speed"))
        self.pushButton_startmv.setText(_translate("Form", "Move!"))

